Repository inspec/kitchen-inspec, pull requests merged in 2020-09, with the labels that each got.

#258 Add ability to disable input caching in InSpec
  README.md
  lib/kitchen/verifier/inspec.rb
Labels: Expeditor: Bump Version Minor, Type: Enhancement

#259 Declare kitchen-inspec to be run serially
  kitchen-inspec.gemspec
  lib/kitchen/verifier/inspec.rb
Labels: Aspect: Stability, Expeditor: Bump Version Minor

#261 Load plugins earlier; load plugins by default
  README.md
  lib/kitchen/verifier/inspec.rb
Labels: Type: Bug
